# #Build and push a docker image from the latest push to "develop" branch
name: backend
on:
  push:
    branches:
      - infrastructure

jobs:
  whatisthecontext:
    runs-on: ubuntu-latest
    name: display the current build & deploy CI context and export useful values
    outputs:
      sha: ${{ steps.contextvals.outputs.sha }}
      built_at: ${{ steps.contextvals.outputs.built_at }} 
      is_dev_deploy: ${{ github.ref == 'infrastructure' }}
    steps:
      - name: Export values
        id: contextvals
        run: |
          SHA=${{ github.sha }}
          BUILT_AT=$(date "+%Y-%m-%d %H:%M:%S%z")
          echo ::set-output name=sha::${SHA:0:8}
          echo ::set-output name=built_at::${BUILT_AT}
  build:
    # we do not rebuild on a release to production rather we just publish the built image at the git SHA we are releaseing from
    # if: github.event_name != 'release'
    needs: whatisthecontext
    runs-on: ubuntu-latest
    name: build & push image
    steps:

      - name: Checkout repo
        uses: actions/checkout@v2

      # - name: Inject build version
      #   working-directory: ./backend
      #   run: |
      #     printf "%s\n" "injecting build version: ${{ needs.whatisthecontext.outputs.sha }}"
      #     printf "%s\n" "BUILD_VERSION=${{ needs.whatisthecontext.outputs.sha }}" > .env
      #     printf "%s\n" "injecting build at timestamp: ${{ needs.whatisthecontext.outputs.built_at }}"
      #     printf "%s" "BUILT_AT=${{ needs.whatisthecontext.outputs.built_at }}" >> .env
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_FOODOASIS_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_FOODOASIS_PASSWORD }}

      - name: build-and-push-image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: foodoasiscicd/backend:${{ needs.whatisthecontext.outputs.sha }}

      - name: built image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy_dev:   
    name: deploy to dev environment
    runs-on: ubuntu-latest
    needs: [whatisthecontext, build]
    #if: ${{ github.event_name != 'release' && needs.whatisthecontext.outputs.is_dev_deploy }}
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

    - name: Pull down currently deployed task-definition
      run: |
        aws ecs describe-task-definition --task-definition foodoasis-task --query taskDefinition > task.json
    - name: Render task-definition template
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task.json
        container-name: foodoasis-container
        image: foodoasiscicd/backend:${{ needs.whatisthecontext.outputs.sha }}

    - name: Deploy to Amazon ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: foodoasis-task
        cluster: foodoasis-cluster
        wait-for-service-stability: true


  # deploy_prd:   
  #   name: deploy to the production environment
  #   runs-on: ubuntu-latest
  #   needs: [whatisthecontext]
  #   if: ${{ github.event_name == 'release' }}
  #   steps:

  #   - name: Configure AWS credentials
  #     uses: aws-actions/configure-aws-credentials@v1
  #     with:
  #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #       aws-region: us-west-2

  #   - name: Pull down currently deployed task-definition
  #     run: |
  #       aws ecs describe-task-definition --task-definition ballotnav --query taskDefinition > task.json
  #   - name: Render task-definition template
  #     id: task-def
  #     uses: aws-actions/amazon-ecs-render-task-definition@v1
  #     with:
  #       task-definition: task.json
  #       container-name: ballotnav
  #       image: ballotnav/ballotnav:${{ needs.whatisthecontext.outputs.sha }}

  #   - name: Deploy to Amazon ECS
  #     uses: aws-actions/amazon-ecs-deploy-task-definition@v1
  #     with:
  #       task-definition: ${{ steps.task-def.outputs.task-definition }}
  #       service: ballotnav-prd
  #       cluster: bn
  #       wait-for-service-stability: true
